"""Backend OpenAPI snapshot package (Contract v1 — Wave 1, Issue #302).

The presence of this package marker enables ``python -m openapi.regen`` to
resolve from CWD=``backend/``. The snapshot itself lives at
``backend/openapi/openapi.json`` and is regenerated by ``regen.py``.
"""
